name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The tag for the release (e.g., v1.0.0)"
        required: true
      release_title:
        description: "The title of the release"
        required: true
      release_description:
        description: "The description of the release"
        required: true
      pre_release:
        description: "Set to true if this is a pre-release"
        required: false
        default: "false"

run-name: Creating Release ${{ inputs.release_tag }}

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2" # Specify the Go version you need

      # Step 3: Make build.sh executable and run it
      - name: Build the application
        run: |
          chmod +x build.sh
          ./build.sh

      # Step 4: Create zip and tar.gz archives
      - name: Archive outputs
        run: |
          zip -r outputs.zip outputs/
          tar -czvf outputs.tar.gz outputs/
     
      # Step 5: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          echo "${REPO_ACCESS_TOKEN}" | gh auth login --with-token

      # Step 6: Create a release and upload assets
      - name: Create GitHub Release
        run: |
          ls outputs/
          gh release create ${{ github.event.inputs.release_tag }} \
            --title "${{ github.event.inputs.release_title }}" \
            --notes "${{ github.event.inputs.release_description }}" \
            $([[ "${{ github.event.inputs.pre_release }}" == "true" ]] && echo "--prerelease") \
            outputs.zip \
            outputs.tar.gz \
            --repo ${{ github.repository }}

      # Step 7: Verify release creation
      - name: Verify Release
        run: |
          gh release view ${{ github.event.inputs.release_tag }} --repo ${{ github.repository }}